## Numpy Argsort, Argmin, Argmax And Other Tips

In [1]:
import numpy as np

In [8]:
a = np.arange(10)

In [9]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = np.array([67,3,5,6,3,2323,3,6,7,43,5,3,23,54,23,54,23,23])

In [36]:
b.shape

(18,)

In [48]:
b = b.reshape(6,3)

In [49]:
b

array([[  67,    3,    5],
       [   6,    3, 2323],
       [   3,    6,    7],
       [  43,    5,    3],
       [  23,   54,   23],
       [  54,   23,   23]])

In [54]:
# b.argsort()
# np.argsort(b, axis=0)
np.argsort(b)

array([[1, 2, 0],
       [1, 0, 2],
       [0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [1, 2, 0]])

In [43]:
np.argmin(b)

1

In [44]:
np.argmax(b)

5