## Basic Functions of Numpy Array

In [1]:
import numpy as np

In [2]:
array1 = np.array([
    [2,1,3,4,8],
    [3,5,6,7,5]
])


In [3]:
print(array1)

[[2 1 3 4 8]
 [3 5 6 7 5]]


In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(2, 5)

In [6]:
array1.dtype

dtype('int64')

In [7]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.empty((3,5))

array([[8.694852e-317, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000]])

In [12]:
array1

array([[2, 1, 3, 4, 8],
       [3, 5, 6, 7, 5]])

In [13]:
array1*array1

array([[ 4,  1,  9, 16, 64],
       [ 9, 25, 36, 49, 25]])

array1+array1

In [14]:
array1-array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
array1**array1

array([[       4,        1,       27,      256, 16777216],
       [      27,     3125,    46656,   823543,     3125]])

In [16]:
2/array1

array([[1.        , 2.        , 0.66666667, 0.5       , 0.25      ],
       [0.66666667, 0.4       , 0.33333333, 0.28571429, 0.4       ]])

## Slicing

In [17]:
array2 = np.array([12,5,5,2,3,57,3])

In [18]:
array2

array([12,  5,  5,  2,  3, 57,  3])

In [19]:
array2[1:4]

array([5, 5, 2])

In [20]:
array2[4:]

array([ 3, 57,  3])

In [21]:
#arr = array2[0:3]
arr = array2[0:3].copy()

In [22]:
arr

array([12,  5,  5])

In [23]:
arr[0] =15

In [24]:
arr

array([15,  5,  5])

In [25]:
array2

array([12,  5,  5,  2,  3, 57,  3])