## Basic Functions of Numpy Array

In [1]:
import numpy as np

In [2]:
# arr1 = np.array([1,2,3,4,5,6,7])
arr1 = np.array([[1,2,3,14,5,6,7], [3,5,6,3,6,4,3]])
# arr1 = np.array([[1,2,3,0.14,5,6,7], [3,5,6,3,6,4,3]])
# arr1 = np.array([[1,2,3,4,5,6,7], [3,5,6,3,6,4,3]], dtype="int32")
print(arr1)
print(type(arr1))

[[ 1  2  3 14  5  6  7]
 [ 3  5  6  3  6  4  3]]
<class 'numpy.ndarray'>


In [3]:
arr1.shape # (row, column)

(2, 7)

In [4]:
arr1.dtype

dtype('int64')

In [5]:
np.zeros((2,4,))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros(4).dtype

dtype('float64')

In [7]:
np.zeros((2,4,), dtype="int32")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [8]:
np.zeros((2,4,), dtype="int32").dtype

dtype('int32')

In [9]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.ones((3,6)).dtype

dtype('float64')

In [11]:
np.ones((3,6), dtype="int64").dtype

dtype('int64')

In [12]:
np.empty((4,6))

array([[9.19921774e-317, 0.00000000e+000, 9.82157975e+252,
        8.89489936e+252, 6.01346954e-154, 6.01347002e-154],
       [6.01347002e-154, 6.01347002e-154, 9.08366793e+223,
        1.14177168e+243, 2.45126797e+198, 1.06083187e-153],
       [2.35625393e+251, 6.01334511e-154, 6.01347002e-154,
        6.01347002e-154, 6.01347002e-154, 1.88556770e+122],
       [4.96820036e+180, 6.80600993e+212, 1.10317376e+217,
        1.19490107e+190, 2.06642651e+161, 5.44760669e-109]])

In [13]:
arr1[0]

array([ 1,  2,  3, 14,  5,  6,  7])

In [14]:
arr1[0]*arr1[1]

array([ 3, 10, 18, 42, 30, 24, 21])

In [15]:
mulArr = np.array(arr1[0]*arr1[1])

In [16]:
mulArr

array([ 3, 10, 18, 42, 30, 24, 21])

In [17]:
mulArr = np.array((arr1[0]*arr1[1]))

In [18]:
mulArr

array([ 3, 10, 18, 42, 30, 24, 21])

In [19]:
arr1[0]*arr1[0][2]

array([ 3,  6,  9, 42, 15, 18, 21])

In [20]:
arr1*arr1

array([[  1,   4,   9, 196,  25,  36,  49],
       [  9,  25,  36,   9,  36,  16,   9]])

In [21]:
arr1+arr1

array([[ 2,  4,  6, 28, 10, 12, 14],
       [ 6, 10, 12,  6, 12,  8,  6]])

In [22]:
arr1-arr1

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [23]:
arr1//arr1

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [24]:
arr1**arr1

array([[                1,                 4,                27,
        11112006825558016,              3125,             46656,
                   823543],
       [               27,              3125,             46656,
                       27,             46656,               256,
                       27]])

In [25]:
arr1++arr1

array([[ 2,  4,  6, 28, 10, 12, 14],
       [ 6, 10, 12,  6, 12,  8,  6]])

In [26]:
arr1--arr1

array([[ 2,  4,  6, 28, 10, 12, 14],
       [ 6, 10, 12,  6, 12,  8,  6]])

In [27]:
2/arr1

array([[2.        , 1.        , 0.66666667, 0.14285714, 0.4       ,
        0.33333333, 0.28571429],
       [0.66666667, 0.4       , 0.33333333, 0.66666667, 0.33333333,
        0.5       , 0.66666667]])

# Slicing

In [28]:
arr1

array([[ 1,  2,  3, 14,  5,  6,  7],
       [ 3,  5,  6,  3,  6,  4,  3]])

In [29]:
arr1[:] # get intire array

array([[ 1,  2,  3, 14,  5,  6,  7],
       [ 3,  5,  6,  3,  6,  4,  3]])

In [30]:
arr1[:1] # get second array

array([[ 1,  2,  3, 14,  5,  6,  7]])

In [31]:
arr1[0][2:]

array([ 3, 14,  5,  6,  7])

In [32]:
arr1[1][0:4]

array([3, 5, 6, 3])

In [33]:
arr1[0][:4]

array([ 1,  2,  3, 14])

In [34]:
arr1[0][:]

array([ 1,  2,  3, 14,  5,  6,  7])

In [35]:
arr1[0][3:]

array([14,  5,  6,  7])

In [36]:
arr = np.array([1,3,5,6,3,4,3,3])

In [37]:
arr[0:3]

array([1, 3, 5])

In [38]:
arr[3:]

array([6, 3, 4, 3, 3])

In [39]:
a = arr[2:4]

In [40]:
a[0] = 1232

In [41]:
arr

array([   1,    3, 1232,    6,    3,    4,    3,    3])

In [42]:
a = arr[2:4].copy()

In [43]:
a[0] = 41

In [44]:
arr

array([   1,    3, 1232,    6,    3,    4,    3,    3])

In [45]:
a

array([41,  6])